apiVersion: v1
kind: Secret
metadata:
  name: travel-mcp-secrets
  namespace: travel-mcp
  labels:
    app.kubernetes.io/name: travel-mcp-secrets
    app.kubernetes.io/part-of: travel-langgraph-agent-mcp
type: Opaque
stringData:
  OPENAI_API_KEY: "XX"
  SERPAPI_API_KEY: "b6262d1a685ce3a1a17fceb0f8323bc3fa38fefdb46d3bf6b51f079da721c7b0"
  DUFFEL_ACCESS_TOKEN: "duffel_test_gf_oyM_otPGZ7D5pg78_QDZe5zMErCmL3vwfp1-kBc1"
  LANGGRAPH_POSTGRES_URI: "postgresql://neondb_owner:npg_nxEPl5hiG3UF@ep-little-wave-atkn1uh7-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
